module.exports=async(cdp,evaluate)=>{
 const results=[];const check=(name,ok)=>{if(!ok)throw Error(name);results.push(name)};
 const pause=ms=>new Promise(r=>setTimeout(r,ms));
 await evaluate('window.sortBaseline=structuredClone(data);window.sortStored=structuredClone(stored)');
 const reset=async(width=1280,height=960)=>{
  await cdp('Emulation.setDeviceMetricsOverride',{width,height,screenWidth:width,screenHeight:height,deviceScaleFactor:1,mobile:width<720});
  await evaluate(`ui.closePromptEditor(true);ui.closePanel();data=structuredClone(sortBaseline);stored=structuredClone(sortStored);ui.openPanel();`);
  await evaluate('ui.settle()');
  await evaluate(`ui.state.activeTab='advanced';ui.state.entryFilter='all';ui.state.search='';ui.state.editorUnlocked=true;ui.render();`);await pause(80);
  await evaluate(`(()=>{const c=ui.shadow.querySelector('.content'),list=ui.shadow.querySelector('.advanced-list');c.scrollTop+=list.getBoundingClientRect().top-c.getBoundingClientRect().top-10;})()`);await pause(80);
 };
 const coords=async(index=0)=>evaluate(`(()=>{const r=ui.shadow.querySelectorAll('.prompt-sort-row')[${index}],h=r.querySelector('.sort-handle').getBoundingClientRect(),b=r.getBoundingClientRect(),c=ui.shadow.querySelector('.content').getBoundingClientRect();return {x:h.x+h.width/2,y:h.y+h.height/2,top:b.top,bottom:b.bottom,cx:c.left,cy:c.top,cb:c.bottom,cr:c.right}})()`);
 const mouse=async(type,x,y)=>cdp('Input.dispatchMouseEvent',{type,x,y,button:type==='mouseMoved'?'none':'left',buttons:type==='mouseReleased'?0:1,clickCount:type==='mouseMoved'?0:1});
 const begin=async()=>{const p=await coords();await mouse('mousePressed',p.x,p.y);await mouse('mouseMoved',p.x+6,p.y+8);await pause(40);return p};
 const settle=async()=>{await evaluate('ui.settle()');await pause(80)};
 await reset();
 check('解锁后每个发送条目有独立44像素拖动柄',await evaluate(`ui.shadow.querySelectorAll('.sort-handle').length===data.prompts.length&&[...ui.shadow.querySelectorAll('.sort-handle')].every(h=>h.getBoundingClientRect().width>=44)`));
 let p=await coords();await mouse('mousePressed',p.x,p.y);await mouse('mouseReleased',p.x,p.y);
 check('点击拖动柄不打开编辑器也不改顺序',await evaluate(`!ui.state.promptEditor&&JSON.stringify(data.prompts.map(p=>p.id))===JSON.stringify(sortBaseline.prompts.map(p=>p.id))`));
 p=await begin();let target=await coords(3);await mouse('mouseMoved',p.x,target.bottom-8);await pause(50);
 check('拖动显示浮层与插入线但尚未写入',await evaluate(`!!ui.shadow.querySelector('.sort-ghost')&&!!ui.shadow.querySelector('.sort-drop-line')&&data.prompts[0].id===sortBaseline.prompts[0].id`));
 require('node:fs').writeFileSync('.ui-review/desktop-sorting.png',Buffer.from((await cdp('Page.captureScreenshot',{format:'png'})).data,'base64'));
 await mouse('mouseReleased',p.x,target.bottom-8);await settle();
 check('鼠标拖动松开后同步当前及持久预设顺序',await evaluate(`data.prompts[3].id===sortBaseline.prompts[0].id&&JSON.stringify(data.prompts.map(p=>p.id))===JSON.stringify(stored.prompts.map(p=>p.id))`));
 check('排序保留所有条目的正文角色开关与深度',await evaluate(`data.prompts.every(p=>JSON.stringify(p)===JSON.stringify(sortBaseline.prompts.find(b=>b.id===p.id)))`));
 check('拖动结束清理浮层和拖动状态',await evaluate(`!ui.shadow.querySelector('.sort-ghost')&&!ui.shadow.querySelector('.sort-drop-line')&&!ui.shadow.querySelector('.sorting-prompts')`));
 await evaluate(`ui.shadow.querySelector('[data-action="sort-undo"]').click()`);await settle();
 check('撤销一次排序同步恢复原位置',await evaluate(`JSON.stringify(data.prompts.map(p=>p.id))===JSON.stringify(sortBaseline.prompts.map(p=>p.id))&&!ui.state.reorderUndo`));
 await reset();p=await begin();await mouse('mouseMoved',p.cx-20,p.y+90);await mouse('mouseReleased',p.cx-20,p.y+90);await settle();
 check('列表外松开取消且不写入',await evaluate(`JSON.stringify(data.prompts)===JSON.stringify(sortBaseline.prompts)`));
 await reset();p=await begin();await cdp('Input.dispatchKeyEvent',{type:'keyDown',key:'Escape',code:'Escape'});await cdp('Input.dispatchKeyEvent',{type:'keyUp',key:'Escape',code:'Escape'});await mouse('mouseReleased',p.x,p.y+120);
 check('Escape只取消拖动并保留设置窗口',await evaluate(`ui.state.open&&!ui.shadow.querySelector('.sort-ghost')&&JSON.stringify(data.prompts)===JSON.stringify(sortBaseline.prompts)`));
 await reset();p=await begin();const scroll=await evaluate(`ui.shadow.querySelector('.content').scrollTop`);await mouse('mouseMoved',p.x,p.cb-8);await pause(350);const scrolled=await evaluate(`ui.shadow.querySelector('.content').scrollTop`);await mouse('mouseReleased',p.cx-20,p.cb-8);
 check('拖动接近下边缘自动滚动',scrolled>scroll+30);
 await reset();p=await begin();target=await coords(2);await evaluate(`data.prompts.reverse();ui.reconcilePreset('外部顺序变化')`);await mouse('mouseReleased',p.x,target.bottom-8);await settle();
 check('原生刷新取消旧拖动而不覆盖新顺序',await evaluate(`data.prompts[0].id===sortBaseline.prompts.at(-1).id&&!ui.shadow.querySelector('.sort-ghost')`));
 await reset();p=await begin();target=await coords(2);await evaluate(`data.prompts.reverse()`);await mouse('mouseReleased',p.x,target.bottom-8);await settle();
 check('未触发刷新事件的并发顺序变化也拒绝覆盖',await evaluate(`data.prompts[0].id===sortBaseline.prompts.at(-1).id&&ui.state.saveMessage.includes('顺序已变化')`));
 await reset();p=await begin();target=await coords(2);await evaluate(`data.prompts[1].content+=String.fromCharCode(10)+'外部新正文'`);await mouse('mouseReleased',p.x,target.bottom-8);await settle();
 check('排序保存合并最新正文改动',await evaluate(`data.prompts.find(p=>p.id===sortBaseline.prompts[1].id).content.endsWith('外部新正文')&&stored.prompts.find(p=>p.id===sortBaseline.prompts[1].id).content.endsWith('外部新正文')`));
 await reset();p=await begin();target=await coords(2);await evaluate(`window.failWrite='in_use'`);await mouse('mouseReleased',p.x,target.bottom-8);await settle();
 check('写入失败回滚顺序并显示错误',await evaluate(`JSON.stringify(data.prompts.map(p=>p.id))===JSON.stringify(sortBaseline.prompts.map(p=>p.id))&&JSON.stringify(stored.prompts.map(p=>p.id))===JSON.stringify(sortStored.prompts.map(p=>p.id))&&ui.state.saveState==='error'`));
 await reset();await evaluate(`ui.state.search='思维链';ui.renderActiveContent()`);
 check('搜索时禁用拖动并提供恢复完整列表入口',await evaluate(`[...ui.shadow.querySelectorAll('.sort-handle')].every(h=>h.disabled)&&!!ui.shadow.querySelector('[data-action="sort-show-all"]')`));
 await evaluate(`ui.shadow.querySelector('[data-action="sort-show-all"]').click()`);
 check('恢复完整列表后重新允许拖动',await evaluate(`!ui.state.search&&ui.state.entryFilter==='all'&&[...ui.shadow.querySelectorAll('.sort-handle')].every(h=>!h.disabled)`));
 await evaluate(`ui.shadow.querySelector('.sort-handle').focus()`);await cdp('Input.dispatchKeyEvent',{type:'keyDown',key:'ArrowDown',code:'ArrowDown',modifiers:1});await cdp('Input.dispatchKeyEvent',{type:'keyUp',key:'ArrowDown',code:'ArrowDown'});await settle();
 check('键盘Alt加方向键可排序',await evaluate(`data.prompts[1].id===sortBaseline.prompts[0].id`));
 await reset(390,844);
 check('触屏仅手柄接管拖动，条目文字保留正常滑动',await evaluate(`getComputedStyle(ui.shadow.querySelector('.sort-handle')).touchAction==='none'&&getComputedStyle(ui.shadow.querySelector('.prompt-row')).touchAction!=='none'`));
 const touch=async(type,x,y)=>cdp('Input.dispatchTouchEvent',{type,touchPoints:type==='touchEnd'||type==='touchCancel'?[]:[{x,y,id:1,radiusX:3,radiusY:3}]});
 p=await coords();await touch('touchStart',p.x,p.y);await pause(40);await touch('touchEnd');await pause(220);
 check('手机短按手柄不误触排序或编辑',await evaluate(`!ui.state.promptEditor&&!ui.shadow.querySelector('.sort-ghost')&&JSON.stringify(data.prompts)===JSON.stringify(sortBaseline.prompts)`));
 await reset(390,844);p=await coords();target=await coords(2);const stillScroll=await evaluate(`ui.shadow.querySelector('.content').scrollTop`);await touch('touchStart',p.x,p.y);await pause(300);
 check('手机按住未移动时不自动滚动',await evaluate(`ui.shadow.querySelector('.content').scrollTop`)===stillScroll);
 check('手机长按手柄显示拖动反馈',await evaluate(`!!ui.shadow.querySelector('.sort-ghost')`));
 require('node:fs').writeFileSync('.ui-review/mobile-sorting.png',Buffer.from((await cdp('Page.captureScreenshot',{format:'png'})).data,'base64'));
 await touch('touchMove',p.x,target.bottom-8);await pause(60);await touch('touchEnd');await settle();
 const touchDebug=await evaluate(`({index:data.prompts.findIndex(p=>p.id===sortBaseline.prompts[0].id),storedIndex:stored.prompts.findIndex(p=>p.id===sortBaseline.prompts[0].id),status:ui.state.saveMessage,ghost:!!ui.shadow.querySelector('.sort-ghost'),errors:window.errors})`);
 if(touchDebug.index!==2)console.log('Touch release debug',p,target,touchDebug);
 check('真实触屏拖动可同步顺序',touchDebug.index===2&&touchDebug.storedIndex===2);
 await reset(390,844);p=await coords();await touch('touchStart',p.x,p.y);await pause(220);await touch('touchCancel');await pause(50);
 check('触屏手势取消后无残留和保存',await evaluate(`!ui.shadow.querySelector('.sort-ghost')&&JSON.stringify(data.prompts)===JSON.stringify(sortBaseline.prompts)`));
 await evaluate(`ui.closePanel();ui.openPanel()`);await settle();
 check('重新打开恢复锁定并隐藏拖动柄',await evaluate(`!ui.state.editorUnlocked&&!ui.shadow.querySelector('.sort-handle')`));
 await reset();await evaluate(`ui.state.editorUnlocked=false;ui.render();`);
 return results;
};
