export const SUMMARY_STYLES = `
.sa-status-grid{display:grid;grid-template-columns:minmax(95px,.45fr) minmax(0,1fr)!important;align-items:start}.sa-status-grid>span{overflow-wrap:anywhere}.sa-status-row{display:contents}.sa-status-grid .sa-status-value{min-width:0}
.sa-block-touch-clone{position:fixed;pointer-events:none;opacity:.85;z-index:2147483640;background:var(--panel)!important}.sa-add-block-btn{padding:10px;border:1px dashed var(--line);background:var(--soft);color:var(--gold);border-radius:8px}.sa-add-block-row{display:flex;gap:8px;flex-wrap:wrap}.sa-block-dragging{opacity:.45}.sa-block-drag-over-top{border-top:3px solid var(--gold)}.sa-block-drag-over-bottom{border-bottom:3px solid var(--gold)}
.summary-slot{min-width:0}.sa-panel{--sa-bg:var(--panel);--sa-surface:var(--panel2);--sa-border:var(--line);--sa-border2:var(--line);--sa-text:var(--ink);--sa-text2:var(--ink);--sa-text3:var(--muted);--sa-primary:var(--gold);--sa-radius:12px;--sa-radius-sm:8px;color:var(--ink);font-size:14px;min-width:0}
.sa-panel *{box-sizing:border-box}.sa-tabs,.sa-btn-group,.sa-footer,.sa-footer-right,.sa-radio-group{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.sa-tabs{margin:14px 0}.sa-tabs button,.sa-btn{padding:8px 12px;border:1px solid var(--line);border-radius:8px;background:var(--soft);color:var(--ink);min-height:36px}.sa-tabs .active,.sa-btn-primary{background:var(--selected);color:var(--gold)}.sa-btn-danger{color:var(--danger)}.sa-btn:disabled{opacity:.5;cursor:default}
.sa-section,.sa-block{border:1px solid var(--line);border-radius:12px;margin-bottom:12px;overflow:hidden;background:var(--surface)}.sa-section-header,.sa-block-header{display:flex;gap:8px;align-items:center;padding:12px;background:var(--soft);flex-wrap:wrap}.sa-section-body,.sa-block-body{padding:12px}.sa-block-header{cursor:pointer}.sa-block-body.collapsed{display:none}.sa-block-actions{display:flex;gap:4px;margin-left:auto}.sa-block-drag{cursor:grab;touch-action:none}.sa-block-role{display:flex;gap:8px;align-items:center}.sa-block-name{flex:1;min-width:90px}.sa-block-name input{width:100%}
.sa-tab-pane,.sa-settings-pane{display:none}.sa-tab-pane.active,.sa-settings-pane.active{display:block}.sa-settings-layout{display:grid;grid-template-columns:130px minmax(0,1fr);gap:16px}.sa-settings-nav{display:flex;flex-direction:column;gap:6px}.sa-settings-nav-item{padding:10px;border-radius:8px;cursor:pointer;color:var(--muted)}.sa-settings-nav-item.active{background:var(--selected);color:var(--gold)}
.sa-row{display:flex;align-items:center;gap:10px;margin:10px 0;flex-wrap:wrap}.sa-label{min-width:90px;color:var(--muted)}.sa-input,.sa-select,.sa-textarea,.sa-block input:not([type=checkbox]),.sa-block textarea,.sa-block select{background:var(--input);color:var(--ink);border:1px solid var(--line);border-radius:7px;padding:9px;min-width:0;max-width:100%}.sa-row>.sa-input{flex:1}.sa-textarea,.sa-block textarea{width:100%;min-height:110px;resize:vertical;line-height:1.5}.sa-row-pair{display:grid;grid-template-columns:repeat(2,minmax(0,1fr))}.sa-pair-item{display:flex;flex-direction:column;gap:6px}.sa-checkbox-grid{display:flex;gap:12px;flex-wrap:wrap;margin:14px 0}.sa-checkbox-grid label,.sa-enable{display:flex;align-items:center;gap:8px;min-height:36px}.sa-no-trans-label{flex-wrap:wrap}.sa-hint,.sa-empty,.sa-status-label{color:var(--muted);line-height:1.6;font-size:12px}.sa-hint{margin:8px 0}.sa-status-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.sa-status-item{padding:8px}.sa-status-value{overflow-wrap:anywhere}.sa-status-bar{margin-bottom:14px}.sa-entry-item,.sa-entry{padding:12px;border-bottom:1px solid var(--line);display:flex;align-items:center;gap:8px;flex-wrap:wrap}.sa-entry-name{flex:1;overflow-wrap:anywhere}.sa-entry-actions{display:flex;gap:6px;flex-wrap:wrap}.sa-entry-disabled{opacity:.65}.sa-footer{justify-content:space-between;padding:16px 0}.sa-drag-over{outline:2px solid var(--gold)}.sa-selection-controls{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0}
@media(max-width:720px){.sa-settings-layout{grid-template-columns:minmax(0,1fr)}.sa-settings-nav{flex-direction:row;overflow-x:auto}.sa-settings-nav-item{white-space:nowrap}.sa-row>.sa-input,.sa-row>.sa-select{width:100%;flex-basis:100%}.sa-input,.sa-select,.sa-textarea,.sa-block textarea{font-size:16px}.sa-status-grid{grid-template-columns:minmax(0,1fr)}.sa-footer-right{width:100%}.sa-footer-right button{flex:1}.sa-row-pair .sa-input{width:100%}}
`;
